version: "3.9"

services:
  database:
    image: postgres:latest
    restart: always
    environment:
      "POSTGRES_PASSWORD": "verySecretPassword"
      "POSTGRES_USER": "administrator"
      "POSTGRES_DB": "db"
    ports:
      - "5432:5432"
